### ISSUE TITLE
Collectd plugins use a mix and match of ip and hostname

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/node-agent#577] opened 2017-08-09 09:37 UTC
The collectd node related plugins are pushing node stats using hostname. On the other hand gluster plugins are pushing stats by ip address. Finally you end up multiple entries in graphite(and in grafana) for the same host which is correct.

**Comment by anmolbabu** [comment] 2017-08-09 09:42
This is not actually a mix of ip and hostname but rather the problem is that:
1. gluster get-state has a field called Peer<peer_no.>.primary_hostname which sometimes gives ip
   (Observed when peer probed using ip).. and using this the cluster stats are pushed
2. The host related stats coming from collectd use hostname as maintained by tendrl

So the fix to this would be to use tendrl maintained "fqdn" for all stats. Have this configured in all plugin configs and use it in the plugins..

**Comment by shtripat** [comment] 2017-08-09 09:46
>> gluster get-state has a field called Peer<peer_no.>.primary_hostname which sometimes gives ip
>> (Observed when peer probed using ip).. and using this the cluster stats are pushed

I agree to this and it solely depends on the way the peer probe was performed. get-state uses the peer name as is to report.

Solution mentioned above would require changes in the way (or the data) we are configuring collectd plugins I feel. Can you detail the changes required here for more clarity?

**Comment by anmolbabu** [comment] 2017-08-09 09:54
We would need additional parameter say peer name in all gluster collectd plugin configuration its value will be equal to node's fqdn as maintained in tendrl and in get_metrics of every plugin, wherever we are using brick.host_name or any such directly from collectd, we'll use this parameter.

**Comment by anmolbabu** [comment] 2017-08-24 07:50
This is no more the case as we have decided to support only the gluster recommendations of using fqdn instead of ip..
Please close this issue @nthomas-redhat

**Closed** 2017-08-31 06:08 UTC
